pr:
- master

variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: outputDirectory
    value: '$(build.binariesDirectory)'

jobs:

- job: Android_Job
  displayName: Xamarin Forms Android CI Build
  pool:
    vmImage: 'windows-2019'
  
  steps:
  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'      

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/MyIncredibleApp.Android.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(BuildConfiguration)'
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'