trigger:
- master

pr:
- master

variables:
  - group: android-keystore-variables
  - name: BuildConfiguration
    value: 'Release'
  - name: outputDirectory
    value: '$(build.binariesDirectory)'    
    
jobs:

- job: Android_Job
  displayName: Xamarin Forms Android CI Build
  pool:
    vmImage: 'windows-2019'
  
  steps:

  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/MyIncredibleApp.Android.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(BuildConfiguration)'
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: 'test'
      projects: '**/MyIncredibleTests.csproj'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '$(outputDirectory)/**/*.apk'
      apksignerKeystoreFile: 'myincredibleappkeystore.jks'
      apksignerKeystorePassword: '$(keystore-password)'
      apksignerKeystoreAlias: '$(keystore-key)'
      apksignerKeyPassword: '$(keystore-key-password)'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(outputDirectory)'
      contents: '**/*.apk'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'AndroidPackage'
      publishLocation: 'Container'