pr:
- master

###################
### Android BUILD
###################
jobs:

- job: Android_Job
  displayName: Xamarin Forms Android CI Build

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
    
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/MyIncredibleApp.Android.csproj'
      createAppPackage: false
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'
  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: 'test'
      projects: '**/MyIncredibleTests.csproj'
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'