pr:
- master

variables:
  - group: android-keystore-variables

###################
### Android BUILD
###################
jobs:

- job: Android_Job
  displayName: Xamarin Forms Android CI Build
  pool:
    vmImage: 'windows-2019'

  steps:

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: 'test'
      projects: '**/MyIncredibleTests.csproj'
      
  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
    
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/MyIncredibleApp.Android.csproj'
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'
  
  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: 'myincredibleappkeystore.jks'
      apksignerKeystorePassword: '$(keystore-password)'
      apksignerKeystoreAlias: '$(keystore-key)'
      apksignerKeyPassword: '$(keystore-key-password)'
  
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(outputDirectory)'
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'AndroidPackage'
      publishLocation: 'Container'
      